### ISSUE TITLE
Crack9K Dataset with 8751 images

### ISSUE THREAD

**Issue by rouchoo** [shengyu27/CrackMamba#3]
Dear Dr. Sheng, 

I found in the train.txt file that the image with Mason prefix seems to be the duplicate name of the existing data, and crack9k is the corresponding image without Mason prefix. We have some questions about this, can you give us some help and explanation？

Thanks.

Best regards.

**Comment by shengyu27** [comment]
Are you downloading version 2.0? If not, it cannot be guaranteed whether the image has been deleted or renamed. If so, then there is indeed an image with a mask prefix.
![image](https://github.com/user-attachments/assets/02685f9f-81d0-4406-9b54-ae011bdd66ef)

**Comment by rouchoo** [comment]
Thank you very much for your help. Could you please copy this link for me? I can't open the v2 data set by following the link in the image. Thank you very much!

**Comment by shengyu27** [comment]
You can carefully review the introduction of the dataset section in the `readme`, or use the link below:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EGIEBY

**Comment by rouchoo** [comment]
Got it !
Thank you very much again.  
With best wishes !
