### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Astro825** [shengyu27/CrackMamba#4]
Hello. May I inquire whether your application for downloading the model weights from the cloud disk is feasible?

**Comment by shengyu27** [comment]
Now it can be downloaded.

**Comment by Astro825** [comment]
I'm sorry, I still can't download it, could you please apply permission for my astrojackson825@gmail.com account through, thanks again!
![image](https://github.com/user-attachments/assets/8a0af267-0123-4035-b47f-f3427f515611)

**Comment by shengyu27** [comment]
Sorry, I forgot to modify the access permission. It is now public.
![image](https://github.com/user-attachments/assets/3580de9a-d8f8-4f9a-9556-43d98cdc1d1d)

**Comment by Astro825** [comment]
Okay, thank you very much!
