### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Astro825** [shengyu27/CrackMamba#5]
What version of numpy are you using?

**Comment by ake020675** [comment]
numba requires numpy<=1.24.
but when i use numpy==1.24.4 or 1.24.1, it shows:
    "no module named numpy.exceptions"

**Comment by ake020675** [comment]
> numba requires numpy<=1.24. but when i use numpy==1.24.4 or 1.24.1, it shows: "no module named numpy.exceptions"

I have upgraded numba version
